
export const metadataKeywords = [
	"fullstack developer",
	"web developer",
	"software engineer",
	"MERN stack",
	"React developer",
	"Node.js engineer",
	"JavaScript specialist",
	"web application developer",
	"frontend developer",
	"backend developer",
	"cloud application architect",
	"REST API developer",
	"scalable web solutions",
	"responsive web design",
	"performance optimization",
	"database engineering",
	"microservices architecture",
	"web performance",
	"enterprise software",
	"modern web technologies",
	"software design",
	"agile development",
	"technical problem solver",
	"system integration",
	"cloud computing",
	"DevOps practices"
];